# Pentagon numbers
# Problem 44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
# and D = |Pk − Pj| is minimised; what is the value of D?

import time
from termcolor import colored
import math

def Pentagonal(i):
    n = i * (3*i - 1) *0.5
    return int(n)

def isPentagonal(i):
    r = ( math.sqrt(1 + 24 * i) + 1 ) / 6
    # print('r=',r,i)
    if int(r) == r:
        print(True)
        return True
    else:
        return False

def main_process():
    i = 1
    flag = True
    result = 0
    while flag:
        i += 1
        n = Pentagonal(i)
        for j in range(i-1,0,-1):
            print('j=',j)
            m = Pentagonal(j)
            print("n,m",n,m)
            if isPentagonal(n -m ) and isPentagonal(n + m):
                result = n-m
                flag = False
                break

    print(colored('mycount=', 'red'), result)

if __name__ == "__main__":
    tic = time.clock()
    
    main_process()

    toc = time.clock()
    print("time=",toc - tic)