# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import math

def fibonacci_iter(limit):
    a, b = 1, 2
    while a < limit:
        yield a
        a, b = b, a+b

if __name__ == "__main__":
    results = []
    # fibonacci_iter(4e6)
    for a in fibonacci_iter(math.pow(10,6)*4):
        # print(a)
        if a % 2 == 0:
            results.append(a)
    print("sum=", sum(results))